#!/usr/bin/env node
// Writes the Cairo files that come from repetitions.json, and checks every token on the way:
//
//   src/repetitions.cairo   the table StressNft's constructor writes to storage
//   tests/golden.cairo      the length and SHA-256 of the token_uri of the tokens the Cairo tests
//                           compare byte for byte (a small one and a large one)
//
// Before writing, it builds each token's token_uri twice (the spliced layout, and naive one-pass
// nesting) and checks that they are equal, that the decoded layers are what the renderer and the
// page produce, and that the score passes the page's MIDI check. Output is deterministic.
//
// Usage: node scripts/gen_fixtures.mjs   (from examples/stress_nft)

import { formatCairo } from "../../../scripts/cairo_format.mjs";
import { writeFileSync } from 'node:fs';
import { checkMidi } from '../../../player/player.js';
import { decodeTokenUri, fillLines } from '../../../scripts/segments.mjs';
import { naiveTokenUri, compositionHtml } from '../../../scripts/composition.mjs';
import { ALIGN, TOKEN_COUNT, defaultRepetitions, rpcResponseBytes, sha256, tokenParts, tokenUri } from './reference.mjs';

/** The tokens whose token_uri the Cairo tests compare with the reference. */
export const GOLDEN_TOKENS = [1, 12];

const bars = defaultRepetitions();
if (bars.length !== TOKEN_COUNT || !bars.every((n) => Number.isInteger(n) && n >= 1 && n < 2 ** 32)) {
  throw new Error('repetitions.json: one positive u32 per token');
}

/** Checks token `id` with `n` bars and returns its token_uri. */
export function checkToken(id, n) {
  const p = tokenParts(id, n);
  const uri = tokenUri(id, n);
  if (uri !== naiveTokenUri(p, ALIGN)) throw new Error(`token ${id}: spliced != naive`);
  const dec = decodeTokenUri(uri);
  if (!dec.svgBytes.equals(Buffer.from(p.svg))) throw new Error(`token ${id}: image != SVG`);
  if (dec.html !== compositionHtml(p, ALIGN)) throw new Error(`token ${id}: animation_url != composed consumer document`);
  if (Object.keys(dec.json).join() !== 'name,description,attributes,image,animation_url') throw new Error('key order');
  checkMidi(p.midi);
  return uri;
}

const rows = ['token  bars   midi bytes  token_uri chars  JSON-RPC response bytes'];
const digests = [];
for (let id = 1; id <= TOKEN_COUNT; id++) {
  const uri = checkToken(id, bars[id - 1]);
  const midi = 48 + 64 * bars[id - 1];
  rows.push(`${String(id).padEnd(7)}${String(bars[id - 1]).padEnd(7)}${String(midi).padEnd(12)}${String(uri.length).padEnd(17)}${rpcResponseBytes(uri)}`);
  if (GOLDEN_TOKENS.includes(id)) digests.push([id, uri.length, sha256(uri)]);
}
console.log(rows.join('\n'));

const here = new URL('../', import.meta.url);
writeFileSync(
  new URL('src/repetitions.cairo', here),
  formatCairo([
    '//! Generated by scripts/gen_fixtures.mjs from repetitions.json. Do not edit.',
    '',
    '/// The calibrated number of bars of token `token_id` (1 to 20): the value StressNft starts with.',
    'pub fn default_repetitions(token_id: u32) -> u32 {',
    '    let table: Array<u32> = array![',
    fillLines(bars.map(String), 8),
    '    ];',
    '    *table.at(token_id - 1)',
    '}',
    '',
  ].join('\n')),
);
writeFileSync(
  new URL('tests/golden.cairo', here),
  formatCairo([
    '//! Generated by scripts/gen_fixtures.mjs from the JS reference. Do not edit.',
    '',
    ...digests.flatMap(([id, len, hash]) => [
      `/// token_uri of token ${id} (${bars[id - 1]} bars): (length, SHA-256).`,
      `pub fn token_uri_${id}_digest() -> (u32, u256) {`,
      `    (${len}, 0x${hash})`,
      '}',
      '',
    ]),
  ].join('\n')),
);
