//! Generated by scripts/gen_fixtures.mjs from repetitions.json. Do not edit.

/// The calibrated number of bars of token `token_id` (1 to 20): the value StressNft starts with.
pub fn default_repetitions(token_id: u32) -> u32 {
    let table: Array<u32> = array![
        6, 36, 76, 175, 261, 374, 573, 772, 971, 1170, 1567, 1965, 2960, 3955, 4949, 6442, 7934,
        9824, 9914, 10023,
    ];
    *table.at(token_id - 1)
}
