//! Generated by scripts/gen_fixtures.mjs from the JS reference. Do not edit.

/// token_uri of token 1 (6 bars): (length, SHA-256).
pub fn token_uri_1_digest() -> (u32, u256) {
    (62625, 0xd91a94358d1b534fadbc2a77c400fe71270053862babbbebc8806f136fbb49a0)
}

/// token_uri of token 12 (1965 bars): (length, SHA-256).
pub fn token_uri_12_digest() -> (u32, u256) {
    (359813, 0x75fce14b6edf67fb1e1c88ca89734ebaec53ffb4df5d063ba9b07ac64b72251a)
}
