//! Generated by scripts/gen_fixtures.mjs from the JS reference. Do not edit.

/// token_uri of token 1 (6 bars): (length, SHA-256).
pub fn token_uri_1_digest() -> (u32, u256) {
    (64321, 0xf969d85ad60d32252f6ead74ae939a3ea4aeb871f32718dfd0bf42afc9413aa9)
}

/// token_uri of token 12 (1965 bars): (length, SHA-256).
pub fn token_uri_12_digest() -> (u32, u256) {
    (361509, 0x942a1ab88ed123fb0e32ea68dbfa9ec72abd6388fd43e7ab944ce9dce87dfc6f)
}
