#!/usr/bin/env node
// @ts-nocheck
// Artifact shape and parity are checked by segments.test.mjs and Cairo goldens.
// Deterministic provider-owned segments. Consumer pages and fixture libraries have separate records.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { formatCairo } from "./cairo_format.mjs";
import { gzipSync } from "fflate";
import { minify } from "terser";
import { gunzipSync } from "node:zlib";
import { ENGINE_PIN, ENGINE_BUILD, engineSource } from "./engine.mjs";
import { gunzip } from "../player/gunzip.js";
import { VERSION, SEGMENT_FORMAT, FIXED_ALIGNMENT, MANIFEST_PATH, b64, bytes, sha256, alignedFragment, segmentFor, cairoBase64Literal, cairoByteArrayConst, licenseText, checkLibraryVersion } from "./segments.mjs";
export const OPTIONS = { ecma: 2020, compress: { passes: 2 }, mangle: true, format: { ascii_only: true } };
export function gzipSource(source) {
  const gzip = Buffer.from(gzipSync(bytes(source), { level: 9, mtime: 0 }));
  if (!gunzipSync(gzip).equals(bytes(source)) || !Buffer.from(gunzip(gzip)).equals(bytes(source))) throw new Error("gzip roundtrip failed");
  return gzip;
}
function flatten(path) {
  return readFileSync(new URL(path, import.meta.url), "utf8").replace(/^import .*?;\n/gm, "").replace(/^export (?=(?:const|function|class|async function) )/gm, "");
}
async function compile(paths, call) {
  const { code } = await minify(`(function(){"use strict";\n${paths.map(flatten).join("\n")}\n${call}();})();`, OPTIONS);
  if (!code || /<\/script|<script|<!--/i.test(code)) throw new Error("unsafe inline source");
  return code;
}
export function gzipFragment(id, gzip) { return `<script type="text/javascript+gzip" id="${id}" src="data:application/gzip;base64,${b64(gzip)}"></script>`; }
export async function build(alignment = FIXED_ALIGNMENT) {
  const engine = engineSource();
  const loader = await compile(["../player/gunzip.js"], "gunzipScripts");
  const wrapper = await compile(["../player/settings.js", "../player/player.js"], "startPlayer");
  const player = engine + "\n;\n" + wrapper;
  const embedded_engine = { offset: 0, length: bytes(engine).length, sha256: sha256(engine) };
  const definitions = {
    gunzip: { source: loader, fragment: `<!-- gunzip: fflate 0.8.3, Copyright (c) 2026 Arjun Barrett, MIT; full license: license() --><script id="onchain-gunzip">${loader}</script>` },
    player: { source: player, gzip: gzipSource(player) },
  };
  definitions.player.fragment = `<!-- TinySynth: Tatsuya Shinyagaito (g200kg), Apache-2.0; Provable Games fork; full notices: license() -->` + gzipFragment("onchain-midi-player", definitions.player.gzip);
  const artifacts = Object.fromEntries(Object.entries(definitions).map(([name, d]) => {
    const raw = alignedFragment(d.fragment, alignment), returned = segmentFor(raw);
    return [name, { ...d, raw, returned, record: { source_sha256: sha256(d.source), source_len: bytes(d.source).length,
      raw_sha256: sha256(raw), raw_len: bytes(raw).length, returned_sha256: sha256(returned), returned_len: returned.length,
      returned_felts: Math.floor(returned.length / 31) + 3,
      ...(name === "player" ? { embedded_engine, wrapper: { offset: bytes(engine).length + 3, length: bytes(wrapper).length, sha256: sha256(wrapper) } } : {}),
      ...(d.gzip ? { gzip_sha256: sha256(d.gzip), gzip_len: d.gzip.length, gzip_base64_len: b64(d.gzip).length } : {}) } }];
  }));
  const license = licenseText();
  const record = { format: SEGMENT_FORMAT, fixed_alignment: alignment, dynamic_alignment: 9,
    toolchain: { fflate: "0.8.3", terser: "5.51.2", minify: OPTIONS, gzip: { level: 9, mtime: 0 } },
    inputs: Object.fromEntries(["player/gunzip.js", "player/settings.js", "player/player.js"].map(path=>[path,{sha256:sha256(readFileSync(new URL(`../${path}`,import.meta.url))),bytes:readFileSync(new URL(`../${path}`,import.meta.url)).length}])),
    engine_build: ENGINE_BUILD, engine_ref: ENGINE_PIN.ref, engine_commit: ENGINE_PIN.commit, script_sha256: ENGINE_PIN.sha256,
    artifacts: Object.fromEntries(Object.entries(artifacts).map(([n, a]) => [n, a.record])),
    license_sha256: sha256(license), license_len: bytes(license).length };
  const cairo = "//! Generated by scripts/build_segments.mjs. DO NOT EDIT.\n"+
    `pub const VERSION: felt252 = '${VERSION}';\npub const SEGMENT_FORMAT: u32 = ${SEGMENT_FORMAT};\npub const ENGINE_SHA256: u256 = 0x${ENGINE_PIN.sha256};\n`+
    Object.entries(artifacts).map(([n,a]) => `pub const ${n.toUpperCase()}_SEGMENT_LEN: u32 = ${a.returned.length};\n`+cairoBase64Literal(`${n}_segment`,a.returned, ["Complete standalone double-base64 fragment."])).join("\n\n")+
    "\n\n"+cairoByteArrayConst("license","LICENSE",license,["Notices and dependency licenses."])+"\n";
  return { artifacts, record, cairo };
}
export async function generatedFiles() {
  const built = await build();
  const files = new Map([["src/segment_data.cairo", built.cairo]]);
  for (const [n,a] of Object.entries(built.artifacts)) files.set(`tests/fixtures/segments/${n}.html`, a.raw);
  const fixtures = {};
  for (const name of ["fixture", "dependent"]) {
    const source = readFileSync(new URL(`../tests/fixtures/libraries/${name}.js`, import.meta.url), "utf8");
    const gzip = gzipSource(source), raw = alignedFragment(gzipFragment(`composition-${name}`,gzip), FIXED_ALIGNMENT);
    const returned = segmentFor(raw);
    files.set(`tests/fixtures/libraries/${name}.html`, raw);
    fixtures[name] = { source_sha256: sha256(source), source_len: bytes(source).length, gzip_sha256: sha256(gzip), gzip_len: gzip.length,
      gzip_base64_len: b64(gzip).length, raw_sha256: sha256(raw), raw_len: bytes(raw).length, returned_sha256: sha256(returned), returned_len: returned.length };
    if (name === "fixture") files.set("tests/fixture_provider.cairo",`//! Independent test-only provider. Never part of TinySynth.\n#[starknet::interface]\npub trait IFixtureProvider<T> { fn library_segment(self: @T) -> ByteArray; }\n#[starknet::contract]\npub mod FixtureProvider {\n    #[storage]\n    struct Storage {}\n    #[abi(embed_v0)]\n    impl Provider of super::IFixtureProvider<ContractState> {\n        fn library_segment(self: @ContractState) -> ByteArray { "${returned}" }\n    }\n}\n`);
  }
  files.set("tests/fixtures/libraries/manifest.json",JSON.stringify({format:SEGMENT_FORMAT,toolchain:built.record.toolchain,libraries:fixtures},null,2)+"\n");
  const ui = await compile(["../examples/beast_consumer/ui.js"], "startUi");
  const style = "html,body{margin:0;height:100%;overflow:hidden;background:#000}#beast-art{position:fixed;inset:0;width:100%;height:100%;object-fit:contain}button{position:fixed;right:12px;bottom:12px;width:48px;height:48px;padding:12px;border:0;z-index:1;border-radius:50%;background:rgba(0,0,0,.55);box-shadow:0 0 0 1px rgba(255,255,255,.4);color:#fff;cursor:pointer}button:disabled{opacity:.4}button svg{width:100%;height:100%;fill:currentColor}p{position:fixed;left:12px;right:64px;bottom:12px;z-index:1;color:#f88;background:#000;font:12px monospace}";
  const owned = {
    head: alignedFragment('<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>Onchain music</title><style>'+style+'</style>'),
    body: alignedFragment('</head><body><button id="play" aria-label="Play" disabled><svg viewBox="0 0 24 24" aria-hidden="true"><path id="icon" d="M8 5v14l11-7z"/></svg></button><p id="error" role="alert" hidden></p>'),
    footer: alignedFragment(`<script id="beast-bootstrap">${ui}</script></body></html>`),
  };
  owned.trusted_body = alignedFragment(owned.body.replace("<body>", '<body data-trusted-art="inline-svg">'));
  for (const [n,raw] of Object.entries(owned)) files.set(`examples/beast_consumer/fixtures/${n}.html`,raw);
  const ownedCairo = "//! NFT-owned pre-encoded document/UI assets. Generated; independent of the MIDI class.\n"+Object.entries(owned).map(([n,raw])=>cairoBase64Literal(`${n}_segment`,segmentFor(raw),["NFT-owned HTML fragment."])).join("\n\n")+"\n";
  files.set("tests/owned_assets.cairo", ownedCairo);
  for (const example of ["beast_consumer","stress_nft"]) files.set(`examples/${example}/src/owned_assets.cairo`,ownedCairo);
  for (const [path, value] of files) if (path.endsWith(".cairo")) files.set(path, formatCairo(value));
  return { ...built, files };
}
if (process.argv[1]?.endsWith("build_segments.mjs")) {
  const check = process.argv.includes("--check"), record = process.argv.includes("--record");
  const result = await generatedFiles();
  const versions = existsSync(MANIFEST_PATH) ? JSON.parse(readFileSync(MANIFEST_PATH,"utf8")) : {};
  const recorded = checkLibraryVersion(versions, VERSION, result.record, { record });
  result.files.set("scripts/library_versions.json",JSON.stringify(recorded,null,2)+"\n");
  let stale = false;
  for (const [path, value] of result.files) {
    const target = new URL(`../${path}`,import.meta.url);
    if (check) { if (!existsSync(target) || readFileSync(target,"utf8") !== value) { console.error(`stale ${path}`); stale = true; } }
    else { mkdirSync(new URL(".",target),{recursive:true}); writeFileSync(target,value); }
  }
  if (stale) process.exitCode=1;
  console.log(JSON.stringify({version:VERSION,artifacts:result.record.artifacts},null,2));
}
