// @ts-check
// Fixtures for the class's own tests, computed by the JS reference (Node's base64 encoder) and
// written by scripts/build_page.mjs:
//
//   tests/class_fixtures.cairo   the raw PAGE (the class stores it only pre-encoded; the tests
//                                re-encode it and compare with animation_url_segment()), base64
//                                vectors for the encoder, and the synthetic scores of
//                                tests/fixtures/midi/scores.json (scripts/gen_midi_fixtures.mjs)
//                                for the gas measurements
//
// The base64 inputs are prefixes of a deterministic byte sequence that the Cairo tests rebuild
// themselves (`seq_bytes`), so only the expected outputs are stored: in full up to 100 bytes, as
// length and SHA-256 beyond.

import { readFileSync } from "node:fs";
import { b64, byteArrayFelts, constFeltArray, fillLines, sha256 } from "./page.mjs";

export const SCORES_PATH = new URL("../tests/fixtures/midi/scores.json", import.meta.url);

/** Prefix lengths whose base64 is stored in full: every length remainder and word boundary. */
export const SHORT_MAX = 100;
/** Larger prefix lengths, pinned by length and SHA-256: around 1 KB, 4 KB, 8 KB and 16 KB. */
export const LONG_LENGTHS = [1023, 1024, 1025, 4096, 8191, 8192, 8193, 16384];

/**
 * The test sequence: the ZX81 generator x -> (75 x + 74) mod 65537 from x = 12345, one byte
 * (x mod 256) per step. Cheap to rebuild in Cairo, and it hits every byte value.
 * @param {number} n
 */
export function seqBytes(n) {
  const out = Buffer.alloc(n);
  let x = 12345;
  for (let i = 0; i < n; i++) {
    x = (75 * x + 74) % 65537;
    out[i] = x % 256;
  }
  return out;
}

/**
 * The synthetic scores, the sizes of the production Beast scores, checked against their recorded
 * sizes and hashes.
 * @returns {Array<{name: string, midi: Buffer}>}
 */
export function beastScores() {
  const { scores } = JSON.parse(readFileSync(SCORES_PATH, "utf8"));
  return scores.map((/** @type {any} */ s) => {
    const midi = Buffer.from(s.midi_b64, "base64");
    if (midi.length !== s.bytes || sha256(midi) !== s.sha256) throw new Error(`${s.name}: MIDI does not match its recorded size and hash`);
    return { name: s.name, midi };
  });
}

/**
 * A `const` felt array and a function deserializing it into a ByteArray.
 * @param {string} fnName
 * @param {string | Uint8Array} x
 * @param {string[]} doc
 */
function byteArrayFn(fnName, x, doc) {
  const constName = fnName.toUpperCase();
  return [
    ...doc.map((l) => `/// ${l}`),
    `pub fn ${fnName}() -> ByteArray {`,
    `    let mut felts = ${constName}.span();`,
    "    let value = Serde::deserialize(ref felts).expect('fixture: bad Serde');",
    "    assert(felts.len() == 0, 'fixture: trailing felts');",
    "    value",
    "}",
    "",
    constFeltArray(constName, byteArrayFelts(x)),
  ].join("\n");
}

/**
 * tests/class_fixtures.cairo.
 * @param {string} page PAGE
 */
export function classFixturesCairo(page) {
  const seq = seqBytes(Math.max(SHORT_MAX, ...LONG_LENGTHS));
  const all = Buffer.from(Array.from({ length: 256 }, (_, i) => i));
  const out = [
    "// Generated by scripts/build_page.mjs (scripts/gen_class_fixtures.mjs). DO NOT EDIT.",
    "//",
    "// Fixtures for the class's tests, computed by the JS reference: the raw PAGE, base64 vectors from",
    "// Node's encoder, and the synthetic scores of tests/fixtures/midi/scores.json.",
    "",
    byteArrayFn("page", page, [
      `PAGE (tests/fixtures/page.html), ${page.length} bytes. The class stores it only pre-encoded;`,
      "`b64('\"animation_url\":\"data:text/html;base64,' ++ b64(page()))` must equal",
      "`animation_url_segment()`.",
    ]),
    "",
    "/// The first `n` bytes of the base64 test sequence: the ZX81 generator",
    "/// `x -> (75 x + 74) mod 65537` from `x = 12345`, one byte (`x mod 256`) per step.",
    "pub fn seq_bytes(n: u32) -> ByteArray {",
    "    let mut out: ByteArray = \"\";",
    "    let mut x: u32 = 12345;",
    "    let mut i = 0;",
    "    while i != n {",
    "        x = (75 * x + 74) % 65537;",
    "        out.append_byte((x % 256).try_into().unwrap());",
    "        i += 1;",
    "    }",
    "    out",
    "}",
    "",
    `/// Standard base64 of \`seq_bytes(n)\` for n = 0..=${SHORT_MAX}, from Node's encoder.`,
    "pub fn seq_b64_short() -> Array<ByteArray> {",
    "    array![",
    fillLines(Array.from({ length: SHORT_MAX + 1 }, (_, n) => `"${b64(seq.subarray(0, n))}"`), 8),
    "    ]",
    "}",
    "",
    "/// `(n, length, SHA-256)` of the standard base64 of `seq_bytes(n)` for larger `n`.",
    "pub fn seq_b64_long() -> Array<(u32, u32, u256)> {",
    "    array![",
    fillLines(LONG_LENGTHS.map((n) => {
      const e = b64(seq.subarray(0, n));
      return `(${n}, ${e.length}, 0x${sha256(e)})`;
    }), 8),
    "    ]",
    "}",
    "",
    "/// Standard base64 of the 256 byte values in order.",
    "pub fn all_bytes_b64() -> ByteArray {",
    `    "${b64(all)}"`,
    "}",
  ];
  for (const { name, midi } of beastScores()) {
    out.push("", byteArrayFn(`beast_midi_${name}`, midi, [`The synthetic score \`${name}\`, ${midi.length} bytes.`]));
  }
  const src = out.join("\n") + "\n";
  // scarb fmt leaves string literals alone: base64 literal lines are the only long lines.
  const long = src.split("\n").find((line) => line.length > 100 && !/^ {4}( {4})?"[A-Za-z0-9+/=]*",?$/.test(line));
  if (long) throw new Error(`generated Cairo line longer than 100 characters: ${long.slice(0, 120)}`);
  return src;
}
