// @ts-nocheck
// Test-only representation/alignment variants; never deployed and never part of TinySynth ABI.
import {readFileSync,writeFileSync} from "node:fs";
import {formatCairo} from "./cairo_format.mjs";
import {build,gzipFragment,gzipSource} from "./build_segments.mjs";
import {alignedFragment,segmentFor,cairoByteArrayConst} from "./segments.mjs";
import {ownedFragment,fixtureFragment} from "./composition.mjs";
const minimum=await build(9),production=await build(279);
import { realBeast, tokenParts } from "../examples/beast_consumer/scripts/reference.mjs";
const real = realBeast(), fullToken = tokenParts(4);
const rawFile=Object.entries(production.artifacts).map(([n,a])=>cairoByteArrayConst(n,n.toUpperCase(),a.raw,[])).join('\n')+'\n'+['head','body','footer'].map(n=>cairoByteArrayConst(n,n.toUpperCase(),ownedFragment(n),[])).join('\n')+'\n'+cairoByteArrayConst('fixture','FIXTURE',fixtureFragment(),[])+'\n'+cairoByteArrayConst('warlock_svg','WARLOCK_SVG',real.svg,[])+'\n'+cairoByteArrayConst('warlock_members','WARLOCK_MEMBERS',fullToken.mem,[])+'\n';
let variant=`//! Test-only minimum-padding provider; artifacts generated by pinned toolchain.\n#[starknet::contract]\npub mod MinimumAlignedTinySynth {\n    use onchain_midi_player::interface::ITinySynth;\n    use onchain_midi_player::types::TinySynthSettings;\n    #[storage]\n    struct Storage {}\n    #[abi(embed_v0)]\n    impl Provider of ITinySynth<ContractState> {\n`;
for(const[n,a]of Object.entries(minimum.artifacts))variant+=`        fn ${n}_segment(self: @ContractState) -> ByteArray { "${a.returned}" }\n`;
variant+=`        fn midi_segment(self: @ContractState, midi: ByteArray, settings: TinySynthSettings) -> ByteArray { onchain_midi_player::segment::midi_segment(midi, @settings) }\n        fn engine(self: @ContractState) -> felt252 { 'tinysynth' }\n        fn version(self: @ContractState) -> felt252 { '0.5.0' }\n        fn script_sha256(self: @ContractState) -> u256 { onchain_midi_player::segment_data::ENGINE_SHA256 }\n        fn license(self: @ContractState) -> ByteArray { onchain_midi_player::segment_data::license() }\n    }\n}\n`;
const fixtureSource=readFileSync(new URL('../tests/fixtures/libraries/fixture.js',import.meta.url),'utf8'),minFixture=segmentFor(alignedFragment(gzipFragment('composition-fixture',gzipSource(fixtureSource)),9));
variant+=`#[starknet::contract]
pub mod MinimumFixtureProvider {
    #[storage]
    struct Storage {}
    #[abi(embed_v0)]
    impl Provider of crate::fixture_provider::IFixtureProvider<ContractState> {
        fn library_segment(self: @ContractState) -> ByteArray { "${minFixture}" }
    }
}
use crate::fixture_provider::{IFixtureProviderDispatcherTrait, IFixtureProviderLibraryDispatcher};
use snforge_std::{DeclareResultTrait, declare};
pub fn minimum_fixture() -> ByteArray {
    IFixtureProviderLibraryDispatcher { class_hash: declare("MinimumFixtureProvider").unwrap().contract_class().class_hash }.library_segment()
}
`;
const assembly=readFileSync(new URL('../tests/assembly.cairo',import.meta.url),'utf8');
const dataFirst=assembly.replace('    uri.append(@bytes_base64_encode(inner));\n    uri.append(@synth.midi_segment(midi, settings));','    uri.append(@synth.midi_segment(midi, settings));\n    uri.append(@bytes_base64_encode(inner));');
for(const[path,raw]of [['tests/raw_assets.cairo',rawFile],['tests/minimum_alignment.cairo',variant],['tests/data_first_assembly.cairo',dataFirst]]){
 const value=formatCairo(raw);
 const url=new URL(`../${path}`,import.meta.url);if(process.argv.includes('--check')){if(readFileSync(url,'utf8')!==value){console.error(`stale ${path}`);process.exitCode=1;}}else writeFileSync(url,value);
}
