import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {test} from "node:test";
import {build,generatedFiles} from "./build_segments.mjs";
import {VERSION,MANIFEST_PATH,FIXED_ALIGNMENT,segmentFor,strictB64Decode,checkLibraryVersion,sha256,fixedFragment,dFragment} from "./segments.mjs";
import {DEFAULT_SETTINGS} from "./settings_fixtures.mjs";
import {consumerPieces,naiveTokenUri} from "./composition.mjs";
test("fixed segments reproduce manifest, complete elements and both canonical unpadded encoding layers",async()=>{const built=await build(),record=JSON.parse(readFileSync(MANIFEST_PATH,"utf8"));assert.deepEqual(record[VERSION],built.record);assert.equal(FIXED_ALIGNMENT,279);for(const[name,a]of Object.entries(built.artifacts)){assert.equal(a.raw,fixedFragment(name));assert.equal(Buffer.byteLength(a.raw)%279,0);assert.equal(a.returned.length%31,0);assert.ok(!a.returned.includes("="));const inner=strictB64Decode(a.returned).toString();assert.ok(!inner.includes("="));assert.equal(strictB64Decode(inner).toString(),a.raw);assert.ok(a.raw.trimEnd().endsWith("</script>"));}});
test("unversioned artifact change is rejected, new version requires explicit record",()=>{const versions={"0.5.0":{format:1}};assert.throws(()=>checkLibraryVersion(versions,"0.5.0",{format:2},{record:true}),/bump VERSION/);assert.throws(()=>checkLibraryVersion(versions,"0.6.0",{format:1}),/--record/);assert.deepEqual(checkLibraryVersion(versions,"0.6.0",{format:1},{record:true})["0.6.0"],{format:1});});
test("dynamic data all lengths/padding residues; generated Cairo golden vectors independently checked",()=>{const pads=new Set();for(let n=0;n<101;n++){const{d,pad}=dFragment(Buffer.alloc(n,0x90),DEFAULT_SETTINGS);pads.add(pad);assert.equal(Buffer.byteLength(d)%9,0);assert.match(d,/^<script type="text\/plain" id="onchain-midi-settings">/);assert.match(d,/<\/script> *$/);const outer=segmentFor(d),inner=strictB64Decode(outer).toString();assert.ok(!outer.includes("=")&&!inner.includes("="));assert.equal(strictB64Decode(inner).toString(),d);}assert.equal(pads.size,9);});
test("independent provider, UTF8 metadata, both art/data orders and scripts after supplied art",()=>{for(const artFirst of[false,true]){const svg='<svg xmlns="http://www.w3.org/2000/svg"><desc>é 🐉 </script></desc></svg>',mem='"name":"音楽 🐉"',d=dFragment(Buffer.alloc(35),DEFAULT_SETTINGS).d,p=consumerPieces(mem,svg,{d,fixture:true,dependent:true,artFirst});assert.equal(p.uri,naiveTokenUri({mem,svg,d},{fixture:true,dependent:true,artFirst}));const json=JSON.parse(strictB64Decode(p.uri.split(',')[1]).toString());assert.equal(json.name,"音楽 🐉");assert.equal(strictB64Decode(json.animation_url.split(',')[1]).toString(),p.html);assert.match(p.html,/<img[^>]+>.*onchain-midi|onchain-midi[\s\S]*<img/);assert.ok(p.html.indexOf('beast-bootstrap')>p.html.indexOf('beast-art'));for(const b of p.boundaries.filter(b=>["fixture","player"].includes(b.name)))assert.equal(b.residue,0);}});
test("release ABI exposes exactly the seven replacement entry points",()=>{
 const abi=JSON.parse(readFileSync(new URL('../abi/TinySynth.json',import.meta.url),'utf8'));
 const names=abi.filter(item=>item.type==='interface').flatMap(item=>item.items.filter(f=>f.type==='function').map(f=>f.name)).sort();
 assert.deepEqual(names,['engine','gunzip_segment','license','midi_segment','player_segment','script_sha256','version']);
});
