#!/usr/bin/env node
// Generates src/mock_page_data.cairo: the mock PAGE, padded and pre-encoded at both base64 layers.
//
// This mirrors the real phase-3 build pipeline, which will do the same around the pinned TinySynth
// engine (after checking its SHA-256): assemble PAGE, pad it to len % 9 == 0, compute
// b64('"animation_url":"data:text/html;base64,' ++ b64(PAGE)) offline, and store the result in the
// class as a constant. Nothing about the page is base64-encoded onchain.
//
// Usage: node scripts/gen_page.mjs   (from examples/beast_consumer). Output is deterministic.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  MOCK_ENGINE_JS, PAGE_VERSION, animationUrlSegment, cairoByteArrayFn, page, pageUnpadded, sha256,
} from './reference.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src', 'mock_page_data.cairo');

const p = page();
const seg = animationUrlSegment();
const pad = p.length - pageUnpadded().length;

const src = `// Generated by scripts/gen_page.mjs. DO NOT EDIT.
//
// Mock stand-in for the real class's page_data.cairo. PAGE (${PAGE_VERSION}) is a tiny HTML
// document: a placeholder for the TinySynth engine, a mock player, and the opening of the settings
// block. It is ${p.length} bytes (${pageUnpadded().length} + ${pad} pad spaces inside the settings block,
// len % 9 == 0).
//
// animation_url_segment() = b64('"animation_url":"data:text/html;base64,' ++ b64(PAGE)),
// ${seg.length} ASCII characters, computed offline.
// sha256(PAGE)    = ${sha256(p)}
// sha256(segment) = ${sha256(seg)}

pub const PAGE_LEN: u32 = ${p.length};
pub const SEGMENT_LEN: u32 = ${seg.length};

/// SHA-256 of the mock engine placeholder script exactly as embedded in PAGE (big-endian). The real
/// class stores the SHA-256 of the pinned TinySynth release here; verification works the same way:
/// decode a token_uri, extract the first <script> of the page, hash it.
pub const ENGINE_SHA256: u256 = 0x${sha256(MOCK_ENGINE_JS)};

${cairoByteArrayFn('animation_url_segment', seg, [
  'The pre-encoded `animation_url` JSON member. Deserializing the stored felts is the cheapest',
  'way to materialize a constant ByteArray; no base64 work happens at call time.',
])}
`;

writeFileSync(out, src);
console.log(`wrote ${out}: PAGE ${p.length} bytes (pad ${pad}), segment ${seg.length} chars`);
