#!/usr/bin/env node
// Builds the reference token_uri for every example token, proves the spliced layout equals plain
// nested base64, and writes:
//
//   tests/golden.cairo           expected token_uri and SVG per token (the Cairo tests assert
//                                byte-for-byte equality with these)
//   fixtures/token_uri.txt       sample token: the exact token_uri string
//   fixtures/token.json          sample token: decoded JSON, pretty-printed
//   fixtures/image.svg           sample token: `image` decoded
//   fixtures/animation.html      sample token: `animation_url` decoded (open it in a browser)
//
// The fixture files are produced by decoding the token_uri string itself (decodeTokenUri), the
// same way a marketplace would, not from the intermediate pieces.
//
// Usage: node scripts/gen_fixtures.mjs   (from examples/beast_consumer). Output is deterministic.

import { mkdirSync, writeFileSync } from 'node:fs';
import { isDeepStrictEqual } from 'node:util';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { ENGINE_SHA256, engineSource } from '../../../scripts/engine.mjs';
import {
  MIDI, TOKENS, animationHtml, blen, bytes, cairoByteArrayFn, decodeTokenUri, page, pageScripts, sha256, tokenJsonCompact,
  tokenParts, tokenUriNaive, tokenUriSpliced, validateMidi,
} from './reference.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SAMPLE_TOKEN = 1;

function check(cond, msg) {
  if (!cond) throw new Error(`check failed: ${msg}`);
}

const midiInfo = validateMidi(MIDI);
console.log(`MIDI: ${MIDI.length} bytes, PPQ ${midiInfo.ppq}, End-of-Track at tick ${midiInfo.eotTick} (${midiInfo.bars} bar)`);
console.log('token  name              headPad  sPad  dPad  token_uri chars');

const ids = Object.keys(TOKENS).map(Number);
const residues = { head: new Set(), s: new Set() };
const golden = [];
for (const id of ids) {
  const p = tokenParts(id);
  const spliced = tokenUriSpliced(id);
  const naive = tokenUriNaive(id);
  // 1. Splicing equals standard nesting, byte for byte.
  check(spliced === naive, `token ${id}: spliced != naive`);
  // 2. The decoded layers are exactly what the renderer and the page produce.
  const dec = decodeTokenUri(spliced);
  check(dec.svgBytes.equals(bytes(p.svg)), `token ${id}: image != render_svg`);
  check(dec.htmlBytes.equals(bytes(page() + p.d + p.svg)), `token ${id}: animation_url != PAGE ++ D ++ SVG`);
  check(dec.html === animationHtml(id), `token ${id}: animation html`);
  // 3. The alignment spaces are insignificant JSON whitespace.
  check(isDeepStrictEqual(dec.json, JSON.parse(tokenJsonCompact(id))), `token ${id}: JSON != compact JSON`);
  check(Object.keys(dec.json).join() === 'name,description,attributes,image,animation_url', 'key order');
  residues.head.add(blen('{' + p.mem + ',') % 3);
  residues.s.add((p.svgB64.length + 1) % 3);
  console.log(`${String(id).padEnd(7)}${p.name.padEnd(18)}${String(p.headPad).padEnd(9)}${String(p.sPad).padEnd(6)}${String(p.dPad).padEnd(6)}${spliced.length}`);
  golden.push(
    cairoByteArrayFn(`token_uri_${id}`, spliced, [
      `Expected token_uri for token ${id} ("${p.name}"), ${spliced.length} chars.`,
      `sha256 = ${sha256(spliced)}`,
    ]),
    cairoByteArrayFn(`svg_${id}`, p.svg, [`Expected render_svg output for token ${id}, ${blen(p.svg)} bytes.`]),
  );
}
// The example tokens are chosen so every consumer pad length (0, 1, 2) occurs.
check(residues.head.size === 3 && residues.s.size === 3, 'tokens must cover all len % 3 residues');

const goldenSrc = `// Generated by scripts/gen_fixtures.mjs. DO NOT EDIT.
//
// Expected outputs computed by the independent JavaScript reference (scripts/reference.mjs), which
// checked for each token that the spliced token_uri equals the whole JSON base64-encoded once
// with standard nested data URIs.

pub const TOKEN_IDS: [u256; ${ids.length}] = [${ids.join(', ')}];

${cairoByteArrayFn('page', page(), [
  `The raw PAGE (${blen(page())} bytes). The class only stores it pre-encoded; the naive`,
  'reference in tests/naive.cairo needs the plain bytes.',
])}

${golden.join('\n\n')}
`;
writeFileSync(join(root, 'tests', 'golden.cairo'), goldenSrc);

// Human-inspectable layers for the sample token, decoded from the token_uri string.
const uri = tokenUriSpliced(SAMPLE_TOKEN);
const dec = decodeTokenUri(uri);
// Verification story of the class: the page's text/javascript+gzip tag carries the gzip payload,
// which inflates to the pinned engine, byte for byte; its SHA-256 is what script_sha256() returns.
const { engine, engineGzip } = pageScripts(dec.html);
check(engine === engineSource() && sha256(engine) === ENGINE_SHA256, 'the page\'s gzip payload inflates to the pinned engine');
console.log(`gzip payload sha256 (GZIP_SHA256): ${sha256(engineGzip)}, ${engineGzip.length} bytes`);
console.log(`engine script sha256 (script_sha256): ${sha256(engine)}`);
const fx = join(root, 'fixtures');
mkdirSync(fx, { recursive: true });
writeFileSync(join(fx, 'token_uri.txt'), uri);
writeFileSync(join(fx, 'token.json'), JSON.stringify(dec.json, null, 2) + '\n');
writeFileSync(join(fx, 'image.svg'), dec.svgBytes);
writeFileSync(join(fx, 'animation.html'), dec.htmlBytes);
console.log(`wrote tests/golden.cairo and fixtures/ (sample token ${SAMPLE_TOKEN}, token_uri sha256 ${sha256(uri)})`);
