//! Pre-encoded page constants (planned, generated).
//!
//! Will be generated by the offline build pipeline and never edited by hand. Planned
//! contents: the fixed HTML page (TinySynth engine + player) pre-encoded at both base64
//! layers for `animation_url_segment`, the engine's SHA-256, the version short string,
//! and the license text. Segment lengths are aligned so the pre-encoded pieces splice
//! into standard base64 without re-encoding.
